const router = require("express").Router();
const AccountController = require("../controllers/AccountController");
router.post("/api/create-account", AccountController.createAccount);
router.get("/api/get-all", AccountController.getListAccount);
router.get("/api/get-one/:id", AccountController.getOneAccountByID);
router.get("/api/login", AccountController.Login);
router.post("/api/changepass", AccountController.changePass);
router.post("/api/changeinfo", AccountController.ChangeInfoAccount);
router.post("/api/verify", AccountController.layLaiPass);
router.get("/api/verify", AccountController.getLayPassVerify);
router.post("/api/verify-end", AccountController.VerifyEnd);
router.get("/api/getvisono", AccountController.getVisono);
module.exports = router;
