const router = require("express").Router();
const AdminController = require("../controllers/AdminController");
router.get("/", AdminController.getAdminDashboard);
router.get("/products", AdminController.getAdminProduct);
router.get("/products/add-product", AdminController.getAdminAddProduct);
router.get("/products/:id", AdminController.getAdminEditProduct);
router.get("/accounts", AdminController.getAdminAccounts);
router.get("/info", AdminController.getAdminInfo);
router.get("/brands", AdminController.getAdminBrand);
router.get("/order", AdminController.getAdminOrder);
router.get("/order/:id", AdminController.getAdminOrderDetail);
module.exports = router;
